"use client";
import {useEffect,useState} from "react";
import {useRouter,useSearchParams} from "next/navigation";
import {SearchIcon} from "@/components/icons";
export function GlobalSearch(){
 const router=useRouter();const params=useSearchParams();const [open,setOpen]=useState(false);const [value,setValue]=useState(params.get("q")||"");
 useEffect(()=>{const handler=(event:KeyboardEvent)=>{if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==="k"){event.preventDefault();setOpen(true);setTimeout(()=>document.getElementById("global-search-input")?.focus(),0);}if(event.key==="Escape")setOpen(false)};window.addEventListener("keydown",handler);return()=>window.removeEventListener("keydown",handler)},[]);
 function submit(e:React.FormEvent){e.preventDefault();const q=value.trim();if(!q)return;setOpen(false);router.push("/search?q="+encodeURIComponent(q))}
 return <div className="hidden md:block"><button type="button" onClick={()=>{setOpen(true);setTimeout(()=>document.getElementById("global-search-input")?.focus(),0)}} className="flex h-10 w-full max-w-md items-center rounded-xl border border-slate-200 bg-slate-50 pl-3 text-left text-slate-400"><SearchIcon size={17}/><span className="ml-4 text-sm">Search decks, cards, tags, collections...</span><span className="ml-auto mr-3 rounded-md border border-slate-200 bg-white px-1.5 py-0.5 text-[10px]">⌘ K</span></button>{open?<div className="fixed inset-0 z-50 bg-slate-950/30 p-5 sm:p-10" onMouseDown={()=>setOpen(false)}><div role="dialog" aria-modal="true" aria-labelledby="global-search-title" className="mx-auto mt-[8vh] max-w-2xl overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-2xl" onMouseDown={e=>e.stopPropagation()}><h2 id="global-search-title" className="sr-only">Global search</h2><form onSubmit={submit} className="flex items-center gap-3 border-b border-slate-100 p-4"><SearchIcon size={18}/><input aria-label="Search decks, cards, tags, collections, creators" id="global-search-input" value={value} onChange={e=>setValue(e.target.value)} placeholder="Search decks, cards, tags, collections, creators..." className="h-10 min-w-0 flex-1 text-sm outline-none"/><button className="rounded-lg bg-slate-950 px-3 py-2 text-xs font-semibold text-white">Search</button></form><div className="p-4 text-xs text-slate-400">Use Enter to search. Esc to close.</div></div></div>:null}</div>
}