import Link from "next/link";
import {AppShell} from "@/components/app-shell";
import {createDeck} from "@/app/decks/actions";
import {createClient} from "@/lib/supabase/server";

export default async function NewDeckPage(){
 const supabase=await createClient();
 const {data:{user}}=await supabase.auth.getUser();
 const {data:workspaces}=user?await supabase.from("workspaces").select("id,name,kind").order("kind"): {data:[]};
 return <AppShell><div className="mx-auto max-w-2xl px-5 py-8 sm:px-8"><Link href="/decks" className="text-sm text-slate-400 hover:text-slate-700">← Back</Link><h1 className="mt-6 text-3xl font-semibold tracking-tight">Create deck</h1><p className="mt-2 text-sm text-slate-500">Choose where this deck belongs.</p><form action={createDeck} className="mt-8 space-y-5 rounded-2xl border border-black/[0.06] bg-white p-6"><label className="block"><span className="text-sm font-medium">Workspace</span><select name="workspace_id" className="mt-2 h-11 w-full rounded-xl border border-slate-200 px-3 text-sm">{(workspaces??[]).map((w:any)=><option key={w.id} value={w.id}>{w.name} · {w.kind}</option>)}</select></label><label className="block"><span className="text-sm font-medium">Name</span><input name="name" required maxLength={120} placeholder="e.g. English B2" className="mt-2 h-11 w-full rounded-xl border border-slate-200 px-3 text-sm outline-none focus:border-slate-400"/></label><label className="block"><span className="text-sm font-medium">Description</span><textarea name="description" rows={4} placeholder="What are you learning?" className="mt-2 w-full rounded-xl border border-slate-200 px-3 py-3 text-sm outline-none focus:border-slate-400"/></label><div className="grid gap-3 sm:grid-cols-2"><input name="category" placeholder="Category e.g. Languages" className="h-10 rounded-xl border border-slate-200 px-3 text-sm"/><input name="subject" placeholder="Subject e.g. Biology" className="h-10 rounded-xl border border-slate-200 px-3 text-sm"/><input name="language" placeholder="Language e.g. en" className="h-10 rounded-xl border border-slate-200 px-3 text-sm"/><select name="difficulty" className="h-10 rounded-xl border border-slate-200 px-3 text-sm"><option value="">Difficulty</option><option>Beginner</option><option>Intermediate</option><option>Advanced</option></select></div><div className="flex justify-end gap-3"><Link href="/decks" className="rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-medium">Cancel</Link><button className="rounded-xl bg-slate-950 px-5 py-2.5 text-sm font-semibold text-white">Create deck</button></div></form></div></AppShell>;
}