import Link from "next/link";
import {notFound} from "next/navigation";
import {AppShell} from "@/components/app-shell";
import {createClient} from "@/lib/supabase/server";
import {deleteDeck,updateDeckSettings} from "@/app/decks/[id]/settings/actions";

export default async function DeckSettingsPage({params,searchParams}:{params:Promise<{id:string}>;searchParams?:Promise<{error?:string;saved?:string}>}){
 const {id}=await params;const query=searchParams?await searchParams:{};
 const supabase=await createClient();
 const {data:{user}}=await supabase.auth.getUser();if(!user)return null;
 const {data:deck}=await supabase.from("decks").select("id,name,description,visibility,owner_id,workspace_id,settings,cards(id),updated_at").eq("id",id).maybeSingle();
 if(!deck)notFound();
 const {data:member}=await supabase.from("workspace_members").select("role").eq("workspace_id",deck.workspace_id).eq("user_id",user.id).maybeSingle();
 if(!["owner","admin","editor"].includes(String(member?.role||"")))return <AppShell><div className="mx-auto max-w-3xl px-5 py-10">You do not have permission to manage this deck.</div></AppShell>;
 const settings=deck.settings||{};
 const cardCount=deck.cards?.length??0;
 return <AppShell><div className="mx-auto max-w-4xl px-5 py-8 sm:px-8"><Link href={"/decks/"+id} className="text-sm text-slate-400">← Deck</Link><h1 className="mt-5 text-3xl font-semibold tracking-tight">Deck settings</h1><p className="mt-2 text-sm text-slate-500">Metadata, appearance, publication and lifecycle controls.</p>
  {query.error?<div className="mt-5 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800">{query.error}</div>:null}{query.saved?<div className="mt-5 rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-800">Deck settings saved.</div>:null}
  <form action={updateDeckSettings.bind(null,id)} className="mt-7 space-y-5 rounded-2xl border border-black/[0.06] bg-white p-6"><label className="block"><span className="text-sm font-medium">Name</span><input name="name" required defaultValue={deck.name} className="mt-2 h-11 w-full rounded-xl border border-slate-200 px-3 text-sm"/></label><label className="block"><span className="text-sm font-medium">Description</span><textarea name="description" defaultValue={deck.description??""} rows={4} className="mt-2 w-full rounded-xl border border-slate-200 px-3 py-3 text-sm"/></label><div className="grid gap-4 sm:grid-cols-2"><select name="visibility" defaultValue={deck.visibility} className="h-11 rounded-xl border border-slate-200 px-3 text-sm"><option value="private">Private</option><option value="unlisted">Unlisted</option><option value="public">Public</option></select><input name="color" defaultValue={settings.color||""} placeholder="Accent color" className="h-11 rounded-xl border border-slate-200 px-3 text-sm"/><input name="icon" defaultValue={settings.icon||""} maxLength={8} placeholder="Icon / emoji" className="h-11 rounded-xl border border-slate-200 px-3 text-sm"/><select name="difficulty" defaultValue={settings.difficulty||""} className="h-11 rounded-xl border border-slate-200 px-3 text-sm"><option value="">Difficulty</option><option>Beginner</option><option>Intermediate</option><option>Advanced</option></select><input name="category" defaultValue={settings.category||""} placeholder="Category" className="h-11 rounded-xl border border-slate-200 px-3 text-sm"/><input name="subject" defaultValue={settings.subject||""} placeholder="Subject" className="h-11 rounded-xl border border-slate-200 px-3 text-sm"/><input name="language" defaultValue={settings.language||""} placeholder="Language" className="h-11 rounded-xl border border-slate-200 px-3 text-sm"/></div><label className="flex items-center gap-3 rounded-xl bg-slate-50 p-3 text-sm"><input type="checkbox" name="archived" defaultChecked={Boolean(settings.archived)} className="h-4 w-4"/><span>Archive this deck</span></label><div className="flex items-center justify-between gap-3"><p className="text-xs text-slate-400">{cardCount} cards · updated {new Date(deck.updated_at).toLocaleString()}</p><button className="rounded-xl bg-slate-950 px-5 py-2.5 text-sm font-semibold text-white">Save settings</button></div></form>
  <section className="mt-5 rounded-2xl border border-red-200 bg-red-50 p-6"><h2 className="font-semibold text-red-900">Permanent deletion</h2><p className="mt-2 text-sm leading-6 text-red-800">This deletes the deck and its dependent cards according to the database foreign-key rules. Export a backup before deleting if the data matters.</p><form action={deleteDeck.bind(null,id)} className="mt-4 flex flex-col gap-2 sm:flex-row"><input name="confirm" placeholder="Type DELETE" className="h-11 flex-1 rounded-xl border border-red-200 bg-white px-3 text-sm"/><button className="rounded-xl bg-red-700 px-5 py-2.5 text-sm font-semibold text-white">Delete deck</button></form></section>
 </div></AppShell>;
}
