import Link from "next/link";
import {AppShell} from "@/components/app-shell";
import {createClient} from "@/lib/supabase/server";
export default async function SearchPage({searchParams}:{searchParams:Promise<{q?:string}>}){
 const {q}=await searchParams;const query=String(q||"").trim();const supabase:any=await createClient();const {data:{user}}=await supabase.auth.getUser();
 if(!query)return <AppShell><div className="mx-auto max-w-4xl px-5 py-10"><h1 className="text-3xl font-semibold">Search</h1><p className="mt-2 text-sm text-slate-500">Press Cmd/Ctrl + K from the top bar to search.</p></div></AppShell>;
 const like="%"+query.replace(/[%_]/g,"\\$&")+"%";
 const [{data:decks},{data:cards},{data:tags},{data:collections},{data:profiles}]=await Promise.all([
  supabase.from("decks").select("id,name,description,visibility,workspace_id").or("name.ilike."+like+",description.ilike."+like).limit(30),
  user?supabase.from("cards").select("id,deck_id,kind,content").or("content->>front.ilike."+like+",content->>back.ilike."+like).limit(50):Promise.resolve({data:[]}),
  user?supabase.from("tags").select("id,name,workspace_id").ilike("name",like).limit(30):Promise.resolve({data:[]}),
  user?supabase.from("collections").select("id,name,kind").ilike("name",like).limit(30):Promise.resolve({data:[]}),
  supabase.from("profiles").select("id,username,display_name,bio").or("username.ilike."+like+",display_name.ilike."+like+",bio.ilike."+like).limit(30)
 ]);
 return <AppShell><div className="mx-auto max-w-6xl px-5 py-8 sm:px-8"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><p className="text-sm text-slate-400">Global search</p><h1 className="mt-1 text-3xl font-semibold">Results for “{query}”</h1></div><Link href="/search" className="text-sm text-slate-500 hover:text-slate-950">New search</Link></div><div className="mt-8 grid gap-5 lg:grid-cols-2">{<ResultSection title="Decks" items={(decks??[]).map((x:any)=>({key:x.id,title:x.name,meta:x.visibility,href:"/decks/"+x.id,body:x.description}))}/>}<ResultSection title="Cards" items={(cards??[]).map((x:any)=>({key:x.id,title:x.content?.front||"Untitled card",meta:x.kind,href:"/decks/"+x.deck_id,body:x.content?.back||""}))}/><ResultSection title="Tags" items={(tags??[]).map((x:any)=>({key:x.id,title:x.name,meta:"tag",href:"/search?q="+encodeURIComponent(x.name)}))}/><ResultSection title="Collections" items={(collections??[]).map((x:any)=>({key:x.id,title:x.name,meta:x.kind,href:"/collections/"+x.id}))}/><ResultSection title="Creators" items={(profiles??[]).map((x:any)=>({key:x.id,title:x.display_name||x.username||"Creator",meta:x.username?"@"+x.username:"creator",href:x.username?"/u/"+x.username:"/settings/profile",body:x.bio||""}))}/></div></div></AppShell>;
}
function ResultSection({title,items}:{title:string;items:{key:string;title:string;meta:string;href:string;body?:string}[]}){return <section className="overflow-hidden rounded-2xl border border-black/[0.06] bg-white"><div className="border-b border-black/[0.05] px-5 py-4"><h2 className="text-sm font-semibold">{title}</h2></div><div>{items.length?items.map((item,index)=><Link href={item.href} key={item.key} className={"block px-5 py-4 hover:bg-slate-50 "+(index?"border-t border-black/[0.05]":"")}><div className="flex items-center justify-between gap-3"><p className="truncate text-sm font-medium">{item.title}</p><span className="shrink-0 text-[10px] font-semibold uppercase tracking-[0.12em] text-slate-400">{item.meta}</span></div>{item.body?<p className="mt-1 line-clamp-2 text-xs leading-5 text-slate-500">{item.body}</p>:null}</Link>):<div className="px-5 py-8 text-center text-xs text-slate-400">No results.</div>}</div></section>}
