import {AppShell} from "@/components/app-shell";
import {createClient} from "@/lib/supabase/server";
import {markAllNotificationsRead,markNotificationRead} from "@/app/notifications/actions";
export default async function NotificationsPage(){
 const supabase:any=await createClient();
 const {data:{user}}=await supabase.auth.getUser();
 if(!user)return <AppShell><div className="mx-auto max-w-3xl px-5 py-10">Sign in to view notifications.</div></AppShell>;
 const {data:notifications}=await supabase.from("notifications").select("id,kind,title,body,href,read_at,created_at").eq("user_id",user.id).order("created_at",{ascending:false}).limit(100);
 return <AppShell><div className="mx-auto max-w-3xl px-5 py-8 sm:px-8"><div className="flex items-end justify-between gap-4"><div><p className="text-sm text-slate-400">Activity</p><h1 className="mt-1 text-3xl font-semibold">Notifications</h1><p className="mt-2 text-sm text-slate-500">Sync, workspace, community and backup activity.</p></div><form action={markAllNotificationsRead}><button className="rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-semibold">Mark all read</button></form></div><div className="mt-7 overflow-hidden rounded-2xl border border-black/[0.06] bg-white">{(notifications??[]).map((n:any,i:number)=><div key={n.id} className={"p-5 "+(i?"border-t border-black/[0.05]":"")+(n.read_at?"":" bg-slate-50/70")}><div className="flex gap-4"><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><span className="rounded-full bg-slate-100 px-2.5 py-1 text-[10px] font-semibold uppercase tracking-[0.12em] text-slate-500">{n.kind}</span>{!n.read_at?<span className="h-2 w-2 rounded-full bg-slate-950"/>:null}</div><h2 className="mt-2 text-sm font-semibold">{n.title}</h2><p className="mt-1 text-sm leading-6 text-slate-500">{n.body}</p><p className="mt-2 text-xs text-slate-400">{new Date(n.created_at).toLocaleString()}</p></div><div className="shrink-0">{!n.read_at?<form action={markNotificationRead.bind(null,n.id)}><button className="text-xs font-semibold text-slate-700">Read</button></form>:n.href?<a href={n.href} className="text-xs font-semibold text-slate-700">Open</a>:null}</div></div></div>)}{!(notifications??[]).length?<div className="p-10 text-center text-sm text-slate-500">You are all caught up.</div>:null}</div></div></AppShell>;
}