import {AppShell} from "@/components/app-shell";
import {createClient} from "@/lib/supabase/server";
import {markAllNotificationsRead,markNotificationRead,saveNotificationPreferences} from "@/app/notifications/actions";

export default async function NotificationsPage({searchParams}:{searchParams?:Promise<{error?:string;saved?:string;kind?:string;unread?:string}>}){
 const params=searchParams?await searchParams:{};
 const supabase:any=await createClient();const {data:{user}}=await supabase.auth.getUser();
 if(!user)return <AppShell><div className="mx-auto max-w-3xl px-5 py-10">Sign in to view notifications.</div></AppShell>;
 let query=supabase.from("notifications").select("id,kind,title,body,href,read_at,created_at").eq("user_id",user.id).order("created_at",{ascending:false}).limit(100);
 if(params.kind)query=query.eq("kind",params.kind);
 if(params.unread==="1")query=query.is("read_at",null);
 const [{data:notifications},{data:preferences}]=await Promise.all([query,supabase.from("notification_preferences").select("*").eq("user_id",user.id).maybeSingle()]);
 const kinds:string[]=Array.from(new Set<string>((notifications??[]).map((n:any)=>String(n.kind))));
 const pref=preferences??{sync_conflicts:true,author_updates:true,workspace_invites:true,collaboration:true,moderation:true,backup:true,offline_state:true,in_app:true};

 return <AppShell><div className="mx-auto max-w-4xl px-5 py-8 sm:px-8">
  <div className="flex items-end justify-between gap-4"><div><p className="text-sm text-slate-400">Activity</p><h1 className="mt-1 text-3xl font-semibold">Notifications</h1><p className="mt-2 text-sm text-slate-500">Sync, workspace, community and backup activity.</p></div><form action={markAllNotificationsRead}><button className="rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-semibold">Mark all read</button></form></div>
  {params.error?<div className="mt-4 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800">{params.error}</div>:null}
  {params.saved?<div className="mt-4 rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-800">Notification preferences saved.</div>:null}
  <form className="mt-6 flex flex-wrap gap-2"><select name="kind" defaultValue={params.kind||""} className="h-10 rounded-xl border border-slate-200 bg-white px-3 text-sm"><option value="">All types</option>{kinds.map(kind=><option key={kind}>{kind}</option>)}</select><label className="flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-3 text-sm"><input name="unread" value="1" type="checkbox" defaultChecked={params.unread==="1"} className="h-4 w-4"/>Unread only</label><button className="rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-semibold text-white">Filter</button></form>
  <div className="mt-7 overflow-hidden rounded-2xl border border-black/[0.06] bg-white">{(notifications??[]).map((n:any,i:number)=><div key={n.id} className={"p-5 "+(i?"border-t border-black/[0.05]":"")+(n.read_at?"":" bg-slate-50/70")}><div className="flex gap-4"><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><span className="rounded-full bg-slate-100 px-2.5 py-1 text-[10px] font-semibold uppercase tracking-[0.12em] text-slate-500">{n.kind}</span>{!n.read_at?<span className="h-2 w-2 rounded-full bg-slate-950"/>:null}</div><h2 className="mt-2 text-sm font-semibold">{n.title}</h2><p className="mt-1 text-sm leading-6 text-slate-500">{n.body}</p><p className="mt-2 text-xs text-slate-400">{new Date(n.created_at).toLocaleString()}</p></div><div className="shrink-0">{!n.read_at?<form action={markNotificationRead.bind(null,n.id)}><button className="text-xs font-semibold text-slate-700">Read</button></form>:n.href?<a href={n.href} className="text-xs font-semibold text-slate-700">Open</a>:null}</div></div></div>)}{!(notifications??[]).length?<div className="p-10 text-center text-sm text-slate-500">No matching notifications.</div>:null}</div>
  <section className="mt-8 rounded-2xl border border-black/[0.06] bg-white p-6"><h2 className="font-semibold">Notification preferences</h2><p className="mt-1 text-sm text-slate-500">Choose which activity types appear in your in-app notification stream.</p><form action={saveNotificationPreferences} className="mt-5 grid gap-3 sm:grid-cols-2">{(["sync_conflicts","author_updates","workspace_invites","collaboration","moderation","backup","offline_state","in_app"] as const).map(field=><label key={field} className="flex items-center gap-3 rounded-xl bg-slate-50 p-3 text-sm"><input type="checkbox" name={field} defaultChecked={Boolean(pref[field])} className="h-4 w-4"/><span>{field.replaceAll("_"," ")}</span></label>)}<div className="sm:col-span-2 flex justify-end"><button className="rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-semibold text-white">Save preferences</button></div></form></section>
 </div></AppShell>;
}
