import {AppShell} from "@/components/app-shell";
import {getReviewStats} from "@/lib/supabase/queries";
export default async function StatisticsPage(){
 const stats=await getReviewStats();
 const maxReviews=Math.max(1,...stats.daily.map((d:any)=>d.reviews));
 return <AppShell><div className="mx-auto max-w-7xl px-5 py-8 sm:px-8"><p className="text-sm text-slate-400">Insights</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">Statistics</h1><p className="mt-2 text-sm text-slate-500">Your review history, accuracy and recent activity.</p>
 <div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[["Reviews",String(stats.reviews)],["Accuracy",stats.accuracy===null?"—":stats.accuracy+"%"],["Study time",stats.studyMinutes+"m"],["Tracked days",String(stats.daily.filter((d:any)=>d.reviews>0).length)]].map(([a,b])=><div key={a} className="rounded-2xl border border-black/[0.06] bg-white p-5"><p className="text-sm text-slate-400">{a}</p><p className="mt-3 text-2xl font-semibold">{b}</p></div>)}</div>
 <div className="mt-8 rounded-2xl border border-black/[0.06] bg-white p-6"><div className="flex items-end justify-between"><div><h2 className="font-semibold">Last 30 days</h2><p className="mt-1 text-xs text-slate-400">Reviews per day</p></div><span className="text-xs text-slate-400">0 → {maxReviews}</span></div><div className="mt-8 flex h-48 items-end gap-1">{stats.daily.map((day:any)=><div key={day.date} className="flex h-full flex-1 flex-col justify-end" title={day.date+" · "+day.reviews+" reviews"}><div className="w-full rounded-t-sm bg-slate-900" style={{height:(day.reviews/maxReviews*100)+"%"}}/></div>)}</div></div>
 <div className="mt-6 overflow-hidden rounded-2xl border border-black/[0.06] bg-white"><div className="border-b border-black/[0.05] px-6 py-4"><h2 className="font-semibold">Daily detail</h2></div><div className="divide-y divide-slate-100">{stats.daily.slice().reverse().slice(0,10).map((day:any)=><div key={day.date} className="flex items-center justify-between px-6 py-4 text-sm"><span>{day.date}</span><span className="text-slate-500">{day.reviews} reviews · {Math.round(day.minutes*10)/10} min · {day.again} again</span></div>)}</div></div>
 </div></AppShell>;
}