import Link from "next/link";
import {AppShell} from "@/components/app-shell";
import {createClient} from "@/lib/supabase/server";
import {createTemplate,updateTemplate,deleteTemplate} from "@/app/decks/[id]/templates/actions";
export default async function TemplatesPage({params}:{params:Promise<{id:string}>}){
 const {id}=await params;const supabase=await createClient();const {data:deck}=await supabase.from("decks").select("id,name").eq("id",id).maybeSingle();if(!deck)return null;
 const {data:templates}=await supabase.from("card_templates").select("id,name,front_template,back_template,css,created_at").eq("deck_id",id).order("created_at");
 return <AppShell><div className="mx-auto max-w-6xl px-5 py-8 sm:px-8"><Link href={"/decks/"+id} className="text-sm text-slate-400">← {deck.name}</Link><h1 className="mt-6 text-3xl font-semibold">Card templates</h1><p className="mt-2 text-sm text-slate-500">Use "+"{{front}}"+" and "+"{{back}}"+" as the default fields, then add your own markup/CSS.</p>
 <form action={createTemplate.bind(null,id)} className="mt-8 rounded-2xl border border-black/[0.06] bg-white p-6"><div className="grid gap-4 md:grid-cols-3"><input name="name" required placeholder="Template name" className="h-11 rounded-xl border px-3 text-sm"/><input name="front_template" defaultValue="{{front}}" className="h-11 rounded-xl border px-3 text-sm"/><input name="back_template" defaultValue="{{back}}" className="h-11 rounded-xl border px-3 text-sm"/></div><textarea name="css" rows={4} placeholder="Optional card CSS" className="mt-4 w-full rounded-xl border px-3 py-3 text-sm"/><button className="mt-4 rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-semibold text-white">Create template</button></form>
 <div className="mt-8 space-y-4">{(templates??[]).map((t:any)=><form action={updateTemplate.bind(null,id,t.id)} key={t.id} className="rounded-2xl border border-black/[0.06] bg-white p-6"><div className="grid gap-4 md:grid-cols-3"><input name="name" defaultValue={t.name} className="h-11 rounded-xl border px-3 text-sm"/><input name="front_template" defaultValue={t.front_template} className="h-11 rounded-xl border px-3 text-sm"/><input name="back_template" defaultValue={t.back_template} className="h-11 rounded-xl border px-3 text-sm"/></div><textarea name="css" defaultValue={t.css} rows={3} className="mt-4 w-full rounded-xl border px-3 py-3 text-sm"/><div className="mt-4 flex justify-end gap-2"><button formAction={deleteTemplate.bind(null,id,t.id)} className="rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-semibold text-slate-500">Delete</button><button className="rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-semibold text-white">Save</button></div></form>)}</div>
 </div></AppShell>;
}