import Link from "next/link";
import {AppShell} from "@/components/app-shell";
import {createClient} from "@/lib/supabase/server";
import {createTemplate,updateTemplate,deleteTemplate,duplicateTemplate,importTemplates} from "@/app/decks/[id]/templates/actions";
import {TemplateEditor} from "@/components/template-editor";
export default async function TemplatesPage({params}:{params:Promise<{id:string}>}){
 const {id}=await params;const supabase=await createClient();const {data:deck}=await supabase.from("decks").select("id,name").eq("id",id).maybeSingle();if(!deck)return null;
 const {data:templates}=await supabase.from("card_templates").select("id,name,front_template,back_template,css,created_at").eq("deck_id",id).order("created_at");
 return <AppShell><div className="mx-auto max-w-6xl px-5 py-8 sm:px-8"><Link href={"/decks/"+id} className="text-sm text-slate-400">← {deck.name}</Link><h1 className="mt-6 text-3xl font-semibold">Card templates</h1><p className="mt-2 text-sm text-slate-500">{"Use {{front}} and {{back}} as the default fields, then add your own markup/CSS."}</p>
 <div className="mt-8 flex flex-wrap gap-2"><a href={"/api/decks/"+id+"/templates/export"} className="rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-semibold">Export templates</a><form action={importTemplates.bind(null,id)} encType="multipart/form-data" className="flex items-center gap-2"><input name="file" type="file" accept=".json,application/json" required className="max-w-56 rounded-xl border border-slate-200 bg-white px-3 py-2 text-xs"/><button className="rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-semibold text-white">Import</button></form></div><form action={createTemplate.bind(null,id)} className="mt-4 rounded-2xl border border-black/[0.06] bg-white p-6"><div className="grid gap-4 md:grid-cols-3"><input name="name" required placeholder="Template name" className="h-11 rounded-xl border px-3 text-sm"/><input name="front_template" defaultValue="{{front}}" className="h-11 rounded-xl border px-3 text-sm"/><input name="back_template" defaultValue="{{back}}" className="h-11 rounded-xl border px-3 text-sm"/></div><textarea name="css" rows={4} placeholder="Optional card CSS" className="mt-4 w-full rounded-xl border px-3 py-3 text-sm"/><button className="mt-4 rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-semibold text-white">Create template</button></form>
 <div className="mt-8 space-y-4">{(templates??[]).map((t:any)=><TemplateEditor key={t.id} template={{id:t.id,name:t.name,front_template:t.front_template,back_template:t.back_template,css:t.css||""}} updateAction={updateTemplate.bind(null,id,t.id)} deleteAction={deleteTemplate.bind(null,id,t.id)} duplicateAction={duplicateTemplate.bind(null,id,t.id)}/>)}</div>
 </div></AppShell>;
}